"""Application Constants"""

# User Types
USER_TYPE_OWNER = "owner"
USER_TYPE_WORKER = "worker"
USER_TYPE_ADMIN = "admin"

USER_TYPES = [USER_TYPE_OWNER, USER_TYPE_WORKER, USER_TYPE_ADMIN]

# Job Status
JOB_STATUS_OPEN = "open"
JOB_STATUS_IN_PROGRESS = "in_progress"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_CANCELLED = "cancelled"

JOB_STATUSES = [
    JOB_STATUS_OPEN,
    JOB_STATUS_IN_PROGRESS,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_CANCELLED
]

# Bid Status
BID_STATUS_PENDING = "pending"
BID_STATUS_ACCEPTED = "accepted"
BID_STATUS_REJECTED = "rejected"
BID_STATUS_COMPLETED = "completed"

BID_STATUSES = [
    BID_STATUS_PENDING,
    BID_STATUS_ACCEPTED,
    BID_STATUS_REJECTED,
    BID_STATUS_COMPLETED
]

# Payment Status
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_COMPLETED = "completed"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_REFUNDED = "refunded"

PAYMENT_STATUSES = [
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_COMPLETED,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_REFUNDED
]

# Notification Types
NOTIFICATION_TYPE_NEW_BID = "new_bid"
NOTIFICATION_TYPE_NEW_MESSAGE = "new_message"
NOTIFICATION_TYPE_BID_ACCEPTED = "bid_accepted"
NOTIFICATION_TYPE_JOB_STARTED = "job_started"
NOTIFICATION_TYPE_JOB_COMPLETED = "job_completed"
NOTIFICATION_TYPE_PAYMENT_RECEIVED = "payment_received"
NOTIFICATION_TYPE_REVIEW_RECEIVED = "review_received"

NOTIFICATION_TYPES = [
    NOTIFICATION_TYPE_NEW_BID,
    NOTIFICATION_TYPE_NEW_MESSAGE,
    NOTIFICATION_TYPE_BID_ACCEPTED,
    NOTIFICATION_TYPE_JOB_STARTED,
    NOTIFICATION_TYPE_JOB_COMPLETED,
    NOTIFICATION_TYPE_PAYMENT_RECEIVED,
    NOTIFICATION_TYPE_REVIEW_RECEIVED,
]

# Worker Availability Status
WORKER_STATUS_AVAILABLE = "available"
WORKER_STATUS_BUSY = "busy"
WORKER_STATUS_OFFLINE = "offline"

WORKER_STATUSES = [
    WORKER_STATUS_AVAILABLE,
    WORKER_STATUS_BUSY,
    WORKER_STATUS_OFFLINE
]

# Payment Methods
PAYMENT_METHOD_STRIPE = "stripe"
PAYMENT_METHOD_MOCK = "mock"
PAYMENT_METHOD_UPI = "upi"

PAYMENT_METHODS = [
    PAYMENT_METHOD_STRIPE,
    PAYMENT_METHOD_MOCK,
    PAYMENT_METHOD_UPI
]

# Admin Actions
ADMIN_ACTION_BLOCK_USER = "user_blocked"
ADMIN_ACTION_UNBLOCK_USER = "user_unblocked"
ADMIN_ACTION_DELETE_JOB = "job_deleted"
ADMIN_ACTION_DELETE_USER = "user_deleted"
ADMIN_ACTION_REFUND_PAYMENT = "payment_refunded"

# Rating Constants
MIN_RATING = 1
MAX_RATING = 5

# Pagination
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Distance (in km) for nearby jobs
DEFAULT_NEARBY_DISTANCE = 50  # km
